name: bitcoin-trading-ai
region: nyc

services:
  - name: bitcoin-ai-web
    source_dir: /
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    environment_slug: docker
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET_KEY
        value: bitcoin_elite_trading_jwt_secret_key_2024_secure_32_chars
      - key: MONGODB_URL
        value: mongodb+srv://admin:SecureBitcoinAI2024!@cluster0.shv9yzq.mongodb.net/btc_trading?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DB
        value: btc_trading

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED 